### ISSUE TITLE
Good casino site like roobet.com

### ISSUE THREAD

**Issue by dawnsee** [dawnsee/Crash-game#1]
This project will be super casino site

**Comment by DawnSee0823** [comment]
I think so this idea is good

**Comment by DawnSee0823** [comment]
yes, good. I will provide soon

**Comment by dawnsee** [comment]
Yeah, I 'm looking for cool investor now

**Comment by DawnSee0823** [comment]
Ok, I have someone who might be interested in this, but I need a much more detailed description of the situation to inform him

**Comment by dawnsee** [comment]
Thanks
So I have good casino project now
but for deploy this site on internet and running on net , I need to get some money that working payment
So I 'm looking for cool man for this
If I found investor , we can get a lot of money like bc.game or roobet.com and get cool profit

**Comment by DawnSee0823** [comment]
Okay, perfect
